# Generated by Django 5.0.3 on 2026-04-19 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.AutoField(db_column='IdReserva', primary_key=True, serialize=False)),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True, db_column='FechaReserva')),
                ('fecha_vencimiento', models.DateTimeField(db_column='FechaVencimiento')),
                ('monto_adelanto', models.DecimalField(db_column='MontoAdelanto', decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(choices=[('Activa', 'Activa'), ('Atendida', 'Atendida'), ('Cancelada', 'Cancelada')], db_column='Estado', default='Activa', max_length=20)),
                ('cliente', models.ForeignKey(db_column='IdCliente', on_delete=django.db.models.deletion.CASCADE, to='usuarios.cliente')),
                ('usuario', models.ForeignKey(db_column='IdUsuario', on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
            options={
                'db_table': 'Reserva',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.AutoField(db_column='IdVenta', primary_key=True, serialize=False)),
                ('fecha_venta', models.DateTimeField(auto_now_add=True, db_column='FechaVenta')),
                ('total_venta', models.DecimalField(db_column='TotalVenta', decimal_places=2, max_digits=10)),
                ('cliente', models.ForeignKey(db_column='IdCliente', on_delete=django.db.models.deletion.CASCADE, to='usuarios.cliente')),
                ('reserva', models.ForeignKey(blank=True, db_column='IdReserva', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.reserva')),
                ('usuario', models.ForeignKey(db_column='IdUsuario', on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
            options={
                'db_table': 'VENTA',
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id_detalle', models.AutoField(db_column='IdDetalle', primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(db_column='PrecioUnitario', decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(db_column='Subtotal', decimal_places=2, max_digits=10)),
                ('producto', models.ForeignKey(db_column='IdProducto', on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
                ('venta', models.ForeignKey(db_column='IdVenta', on_delete=django.db.models.deletion.CASCADE, to='ventas.venta')),
            ],
            options={
                'db_table': 'DETALLEVENTA',
            },
        ),
    ]
