# Generated by Django 5.0.3 on 2026-04-19 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(db_column='IdProducto', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=150)),
                ('marca', models.CharField(blank=True, max_length=50, null=True)),
                ('modelo', models.CharField(blank=True, db_column='Modelo', max_length=50, null=True)),
                ('año', models.IntegerField(blank=True, null=True)),
                ('precio_actual', models.DecimalField(blank=True, db_column='PrecioActual', decimal_places=2, max_digits=10, null=True)),
                ('stock_fisico', models.IntegerField(default=0)),
                ('stock_reservado', models.IntegerField(default=0)),
                ('estado', models.CharField(blank=True, choices=[('Nuevo', 'Nuevo'), ('Seminuevo', 'Seminuevo'), ('Usado', 'Usado'), ('Obsoleto', 'Obsoleto')], max_length=20, null=True)),
            ],
            options={
                'db_table': 'PRODUCTO',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(blank=True, max_length=100, null=True)),
                ('nit', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'Proveedor',
            },
        ),
    ]
