# Generated by Django 5.0.3 on 2026-04-19 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id_persona', models.AutoField(db_column='IdPersona', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=100, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'Persona',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('persona', models.OneToOneField(db_column='IdCliente', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='usuarios.persona')),
                ('nit', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'Cliente',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('persona', models.OneToOneField(db_column='idUsuario', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='usuarios.persona')),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('employee', 'Empleado / Vendedor'), ('client', 'Cliente')], max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('password_hash', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Usuario',
            },
        ),
    ]
